import "dotenv/config"

export const config = {
  host: process.env.HOST ?? "localhost:8080",
  token: process.env.TOKEN,
  tokenB: process.env.TOKEN_B,
  name: process.env.NAME ?? "WHO??",
  minParcelConfidence: 0.3,
  minCarryCapacity: 3,
  maxCarryCapacity: 10,
  switchThreshold: 1.25,
  deliveryDistanceLock: 2,
  lambdaDistanceDecay: 0.3,
  lambdaTimeDecay: 0.03,
  agentStealRiskWeight: 0.6,
  rewardDecayPerStep: 0.2,
  sensingRange: 5,
  sensorMissProbability: 0.2,
  usePlanner: true,
  plannerUrl: process.env.PLANNER_URL,
  plannerTimeoutMs: 4000,
  reconsiderEveryStep: true,
  enableComms: true,
  useSocketComms: true,
  peerClaimTtlMs: 10000,
  statusReportIntervalMs: 500,
  llmBaseURL: process.env.LLM_BASE_URL,
  llmApiKey: process.env.LLM_API_KEY,
  llmModel: process.env.LLM_MODEL,
  maxRetries: 3,
}
